work_dir: ./work_dir/ntu_25/xsub/aagcn_joint
model_saved_name: ./runs/ntu_25_cs_aagcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu_25/xsub/train_data_joint.npy
  label_path: ./data/ntu_25/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu_25/xsub/val_data_joint.npy
  label_path: ./data/ntu_25/xsub/val_label.pkl

# model
model: model.aagcn_mesh.Model
model_args:
  num_class: 49
  num_point: 25
  num_person: 1
  graph: graph.ntu_mesh.MeshGraph
  graph_args:
    labeling_mode: 'spatial'
    inward: 'data/ntu_25/inward.pt'
#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]
warm_up_epoch: 5

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 500
nesterov: True

only_train_part: True
only_train_epoch: 5