work_dir: ./work_dir/ntu_2095/xsub/aagcn_joint
model_saved_name: ./runs/ntu_2095_cs_aagcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /mnt/d/yzk/NTU/mesh_pt_11_classes_aagcn/xsub/x_train_2095.npy
  label_path: /mnt/d/yzk/NTU/mesh_pt_11_classes_aagcn/xsub/y_train_2095.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /mnt/d/yzk/NTU/mesh_pt_11_classes_aagcn/xsub/x_test_2095.npy
  label_path: /mnt/d/yzk/NTU/mesh_pt_11_classes_aagcn/xsub/y_test_2095.npy

# model
model: model.aagcn_mesh.Model
model_args:
  num_class: 11
  num_point: 2095
  num_person: 1
  graph: graph.ntu_mesh.MeshGraph
  graph_args:
    labeling_mode: 'spatial'
    inward: '/mnt/d/yzk/NTU/mesh_pt_11_classes_aagcn/xsub/inward.pt'
#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]
warm_up_epoch: 0

# training
device: [0]
batch_size: 4
test_batch_size: 4
num_epoch: 200
nesterov: True

only_train_part: True
only_train_epoch: 5