work_dir: ./work_dir/aagcn_skl/xsub/aagcn_joint
model_saved_name: ./runs/ntu_less_cs_aagcn_joint
# classes: /mnt/h/Datasets/NTU/aagcn_skl/classes.txt
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /mnt/h/Datasets/NTU/aagcn_skl/xsub/train_data_joint.npy
  label_path: /mnt/h/Datasets/NTU/aagcn_skl/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /mnt/h/Datasets/NTU/aagcn_skl/xsub/val_data_joint.npy
  label_path: /mnt/h/Datasets/NTU/aagcn_skl/xsub/val_label.pkl

# model
model: model.aagcn.Model
model_args:
  num_class: 11
  num_point: 25
  num_person: 1
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]
warm_up_epoch: 5

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 200
nesterov: True

only_train_part: False
only_train_epoch: 0