work_dir: ./work_dir/aagcn_mesh_nr/xsub/aagcn_joint
model_saved_name: ./runs/aagcn_mesh_nr_cs_aagcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /mnt/d/yzk/NTU/aagcn_mesh_nr/xsub/train_data_joint.npy
  label_path: /mnt/d/yzk/NTU/aagcn_mesh_nr/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /mnt/d/yzk/NTU/aagcn_mesh_nr/xsub/val_data_joint.npy
  label_path: /mnt/d/yzk/NTU/aagcn_mesh_nr/xsub/val_label.pkl

# model
model: model.aagcn_mesh.Model
model_args:
  num_class: 11
  num_point: 524
  num_person: 1
  graph: graph.ntu_mesh.MeshGraph
  graph_args:
    labeling_mode: 'spatial'
    inward: '/mnt/d/yzk/NTU/aagcn_mesh_nr/inward.pt'
#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]
warm_up_epoch: 0

# training
device: [0]
batch_size: 16
test_batch_size: 16
num_epoch: 200
nesterov: True

only_train_part: True
only_train_epoch: 5